# ClinVar EDA

Raw parquet from `python src/ingest_clinvar.py`.

In [1]:
from pathlib import Path
import pandas as pd

In [2]:

project_root = Path("/home/milijanas/projects/genomic-rag-assistant")
CLINVAR_PARQUET = project_root / "data/raw/clinvar_reliable_grch38.parquet"

In [3]:
df = pd.read_parquet(CLINVAR_PARQUET)
df.shape

(21870, 15)

In [3]:
df.head(1)

,Type,Name,GeneSymbol,HGNC_ID,ClinicalSignificance,LastEvaluated,PhenotypeIDS,PhenotypeList,Assembly,Chromosome,Start,Stop,ReviewStatus,NumberSubmitters,VariationID
0,Indel,NM_014855.3(AP5Z1):c.80_83delinsTGCTGTAAACTGTA...,AP5Z1,HGNC:22197,Pathogenic/Likely pathogenic,"Dec 17, 2024","MONDO:MONDO:0013342,MedGen:C3150901,OMIM:61364...",Hereditary spastic paraplegia 48|Macular dystr...,GRCh38,7,4781213,4781216,"criteria provided, multiple submitters, no con...",4,2

In [5]:
df[df['VariationID']==54970]

,Type,Name,GeneSymbol,HGNC_ID,ClinicalSignificance,LastEvaluated,PhenotypeIDS,PhenotypeList,Assembly,Chromosome,Start,Stop,ReviewStatus,NumberSubmitters,VariationID
3995,single nucleotide variant,NM_007294.4(BRCA1):c.3708T>G (p.Asn1236Lys),BRCA1,HGNC:1100,Benign,"Jun 18, 2019","MONDO:MONDO:0003582,MeSH:D061325,MedGen:C06777...",Hereditary breast ovarian cancer syndrome|Brea...,GRCh38,17,43091823,43091823,reviewed by expert panel,37,54970

In [4]:
df['Type'].value_counts(dropna=False).head(20)

Type
single nucleotide variant    633592
Deletion                      26109
Duplication                   11525
Microsatellite                 7601
Indel                          2512
Insertion                      1576
Inversion                       207
Variation                        73
copy number loss                 25
copy number gain                 11
Name: count, dtype: int64

In [ ]:
# df['ReferenceAllele'].value_counts(dropna=False).head(20)  # all empty
# df['AlternateAllele'].value_counts(dropna=False).head(20)  # all empty

In [5]:
df['ReviewStatus'].value_counts(dropna=False)

ReviewStatus
criteria provided, multiple submitters, no conflicts    661361
reviewed by expert panel                                 21816
practice guideline                                          54
Name: count, dtype: int64

In [6]:
df['ClinicalSignificance'].value_counts(dropna=False)

ClinicalSignificance
Uncertain significance                                                                          299085
Likely benign                                                                                   130872
Benign                                                                                           93342
Benign/Likely benign                                                                             63897
Pathogenic                                                                                       42011
Pathogenic/Likely pathogenic                                                                     39199
Likely pathogenic                                                                                14358
Uncertain significance/Uncertain risk allele                                                       142
drug response                                                                                      106
Pathogenic; drug response                                                                           39
Uncertain significance/VUS-high                                                                     14
Likely pathogenic/Likely risk allele                                                                13
Benign/Likely benign; other                                                                         12
Likely benign; other                                                                                11
Likely pathogenic; drug response                                                                    11
Benign; other                                                                                       10
Uncertain significance/VUS-mid                                                                       7
Pathogenic/Likely pathogenic/Pathogenic, low penetrance                                              6
Pathogenic/Likely risk allele                                                                        6
Uncertain significance; drug response                                                                5
Pathogenic; other                                                                                    5
Pathogenic/Pathogenic, low penetrance                                                                5
Pathogenic/Likely pathogenic/Likely risk allele                                                      5
Likely pathogenic/Pathogenic, low penetrance                                                         5
Likely benign; drug response; other                                                                  4
Pathogenic/Likely pathogenic; other                                                                  4
Uncertain significance; other                                                                        4
Pathogenic/Likely pathogenic; risk factor                                                            4
Pathogenic/Likely pathogenic, low penetrance                                                         4
Likely pathogenic/Likely pathogenic, low penetrance                                                  4
Benign; drug response                                                                                3
Benign; association                                                                                  3
Benign/Likely benign; drug response; other                                                           3
Likely pathogenic; risk factor                                                                       2
Benign/Likely benign; association                                                                    2
Benign/Likely benign; drug response                                                                  2
Benign; risk factor                                                                                  2
Uncertain significance/VUS-low                                                                       2
Pathogenic/Likely pathogenic/Pathogenic, low penetrance/Established risk allele; risk factor         1
Conflicting classifications of pathogenicity; drug response                                          1
Pathogenic/Likely pathogenic/Likely pathogenic, low penetrance                                       1
Benign/Likely benign; other; risk factor                                                             1
Likely pathogenic; association                                                                       1
drug response; other                                                                                 1
Benign/Likely benign; risk factor                                                                    1
Pathogenic; risk factor                                                                              1
Conflicting classifications of pathogenicity                                                         1
VUS-high                                                                                             1
Pathogenic/Likely pathogenic; association                                                            1
not provided                                                                                         1
other                                                                                                1
Pathogenic/Likely pathogenic; drug response                                                          1
Pathogenic/Pathogenic, low penetrance; other                                                         1
Likely benign; association                                                                           1
Likely benign; risk factor                                                                           1
Benign; confers sensitivity                                                                          1
Pathogenic/Likely pathogenic/Established risk allele                                                 1
Uncertain significance; Affects                                                                      1
Uncertain significance; association                                                                  1
Uncertain significance; risk factor                                                                  1
Name: count, dtype: int64

In [7]:
df['PhenotypeList'].value_counts(dropna=False).head(20)

PhenotypeList
not provided                                                                            83128
not provided|Inborn genetic diseases                                                    31724
not provided|not specified                                                              23868
not specified|not provided                                                              13663
Inborn genetic diseases|not provided                                                     9809
not provided|Hereditary cancer-predisposing syndrome                                     4937
Hereditary cancer-predisposing syndrome|not provided                                     3424
Hereditary cancer-predisposing syndrome                                                  2508
Hereditary cancer-predisposing syndrome|Familial adenomatous polyposis 1                 2474
not provided|Cardiovascular phenotype                                                    2463
Cardiovascular phenotype|not provided                                                    2189
Hereditary cancer-predisposing syndrome|Familial cancer of breast                        2160
Familial cancer of breast|Hereditary cancer-predisposing syndrome                        1924
Hereditary nonpolyposis colorectal neoplasms|Hereditary cancer-predisposing syndrome     1713
Gastrointestinal stromal tumor|Hereditary cancer-predisposing syndrome                   1580
Neuroblastoma, susceptibility to, 3|Hereditary cancer-predisposing syndrome              1514
Hereditary cancer-predisposing syndrome|Hereditary nonpolyposis colorectal neoplasms     1484
Primary ciliary dyskinesia                                                               1395
Fanconi anemia|Inborn genetic diseases                                                   1381
Hereditary cancer-predisposing syndrome|Ataxia-telangiectasia syndrome                   1357
Name: count, dtype: Int64

In [8]:
df_tmp = df[
    df["PhenotypeList"].isna() | (df["PhenotypeList"] == "not provided") | (df["PhenotypeList"] == "not specified")
]
df_tmp['ClinicalSignificance'].value_counts(dropna=False)

ClinicalSignificance
Benign                          45942
Likely benign                   18981
Uncertain significance          12101
Benign/Likely benign             4731
Pathogenic                        991
Pathogenic/Likely pathogenic      856
Likely pathogenic                 318
Likely benign; other                4
Name: count, dtype: int64

In [9]:
df_tmp = df[df["ClinicalSignificance"] == "Uncertain significance"]
df_tmp['PhenotypeList'].value_counts(dropna=False)

PhenotypeList
not provided|Inborn genetic diseases                                                                                                                   27978
not provided|not specified                                                                                                                             15308
not provided                                                                                                                                           11633
Inborn genetic diseases|not provided                                                                                                                    7994
not specified|not provided                                                                                                                              5586
                                                                                                                                                       ...
not provided|X-linked severe congenital neutropenia;Thrombocytopenia 1;Wiskott-Aldrich syndrome                                                            1
Hereditary cancer-predisposing syndrome|Cowden syndrome 3;Pheochromocytoma;Carney-Stratakis syndrome;Paragangliomas with sensorineural hearing loss        1
Inborn genetic diseases|Hereditary spastic paraplegia 43                                                                                                   1
not provided|Pulmonary hypertension, primary, 7                                                                                                            1
not provided|Houge-Janssens syndrome 3                                                                                                                     1
Name: count, Length: 59170, dtype: Int64