# UniProt EDA

Raw parquet from `python src/ingest_uniprot.py`.

In [ ]:
from pathlib import Path
import pandas as pd

In [ ]:
project_root = Path("/home/milijanas/projects/genomic-rag-assistant")

UNIPROT_PARQUET = project_root / "data/raw/uniprot_human_reviewed.parquet"

In [2]:
df = pd.read_parquet(UNIPROT_PARQUET)
df.shape

(20431, 17)

In [4]:
df.head(1)

,Entry,Entry Name,Gene Names,Protein names,Length,Function [CC],Involvement in disease,Subcellular location [CC],Interacts with,Domain [FT],Region,Zinc finger,Domain [CC],Natural variant,Polymorphism,Tissue specificity,Developmental stage
0,A0A087X1C5,CP2D7_HUMAN,CYP2D7,Cytochrome P450 2D7 (EC 1.14.14.1),515,FUNCTION: May be responsible for the metabolis...,None,SUBCELLULAR LOCATION: Membrane {ECO:0000305}; ...,None,None,None,None,None,"VARIANT 70; /note=""S -> N (in dbSNP:rs11090077...",POLYMORPHISM: One study shows that a rare doub...,TISSUE SPECIFICITY: Expressed in brain cortex ...,None

In [5]:
df[df["Gene Names"].str.contains("BRCA", na=False)]
df[df["Gene Names"].str.contains("ERVK-19", na=False)]
df[(df['Entry'] == 'P08865') | (df['Entry'] == 'A0A8I5KQE6')]

,Entry,Entry Name,Gene Names,Protein names,Length,Function [CC],Involvement in disease,Subcellular location [CC],Interacts with,Domain [FT],Region,Zinc finger,Domain [CC],Natural variant,Polymorphism,Tissue specificity,Developmental stage
8,A0A8I5KQE6,RPSA2_HUMAN,RPSA2 RPSA RPSAP58,Small ribosomal subunit protein uS2B (37 kDa l...,295,FUNCTION: Required for the assembly and/or sta...,None,SUBCELLULAR LOCATION: Cell membrane {ECO:00002...,None,None,"REGION 54..113; /note=""Interaction with PPP1R1...",None,None,None,None,None,None
2358,P08865,RSSA_HUMAN,RPSA LAMBR LAMR1,Small ribosomal subunit protein uS2 (37 kDa la...,295,FUNCTION: Required for the assembly and/or sta...,"DISEASE: Asplenia, isolated congenital (ICAS) ...",SUBCELLULAR LOCATION: Cell membrane. Cytoplasm...,Q8IYE1; P02489; Q9UQC2; P04792; Q15046; Q9Y2W7...,None,"REGION 54..113; /note=""Interaction with PPP1R1...",None,None,"VARIANT 54; /note=""T -> N (in ICAS; reduced pr...",None,None,None

In [8]:
df['Function [CC]'].head(20).to_list()
# df['Involvement in disease'].head(20).to_list()
# df['Tissue specificity'].head(20).to_list()

['FUNCTION: May be responsible for the metabolism of many drugs and environmental chemicals that it oxidizes. It may be involved in the metabolism of codeine to morphine (PubMed:15051713). However, another study could not confirm it (PubMed:18838503). {ECO:0000269|PubMed:15051713, ECO:0000269|PubMed:18838503}.',
 'FUNCTION: May play a role in cell viability. {ECO:0000269|PubMed:34445188}.',
 'FUNCTION: Plays a role in regulation of the unfolded protein response triggered by endoplasmic reticulum (ER) stress resulting from the presence of unfolded proteins in the ER lumen. {ECO:0000269|PubMed:31653868}.',
 "FUNCTION: Regulates insulin sensitivity and metabolic homeostasis (PubMed:25738459, PubMed:33468709). Inhibits the folate cycle, thereby reducing de novo purine biosynthesis which leads to the accumulation of the de novo purine synthesis intermediate 5-aminoimidazole-4-carboxamide (AICAR) and the activation of the metabolic regulator 5'-AMP-activated protein kinase (AMPK) (PubMed:25738459). Protects against age-dependent and diet-induced insulin resistance as well as diet-induced obesity (PubMed:25738459). In response to metabolic stress, translocates to the nucleus where it binds to antioxidant response elements (ARE) present in the promoter regions of a number of genes and plays a role in regulating nuclear gene expression in an NFE2L2-dependent manner and increasing cellular resistance to metabolic stress (PubMed:29983246). Increases mitochondrial respiration and levels of CPT1A and cytokines IL1B, IL6, IL8, IL10 and TNF in senescent cells (PubMed:29886458). Increases activity of the serine/threonine protein kinase complex mTORC2 and reduces activity of the PTEN phosphatase, thus promoting phosphorylation of AKT (PubMed:33554779). This promotes AKT-mediated phosphorylation of transcription factor FOXO1 which reduces FOXO1 activity, leading to reduced levels of MSTN and promotion of skeletal muscle growth (PubMed:33554779). Promotes osteogenic differentiation of bone marrow mesenchymal stem cells via the TGFB/SMAD pathway (PubMed:30468456). Promotes osteoblast proliferation and osteoblast synthesis of type I collagens COL1A1 and COL1A2 via the TGFB/SMAD pathway (PubMed:31081069). {ECO:0000269|PubMed:25738459, ECO:0000269|PubMed:29886458, ECO:0000269|PubMed:29983246, ECO:0000269|PubMed:30468456, ECO:0000269|PubMed:31081069, ECO:0000269|PubMed:33468709, ECO:0000269|PubMed:33554779}.",
 'FUNCTION: May play an important role in innate immunity by mediating a signal for the production of a neutrophil chemoattractant. {ECO:0000269|PubMed:26221034}.',
 'FUNCTION: Promotes dispersal of P-body components and is likely to play a role in the mRNA decapping process. {ECO:0000269|PubMed:27918561}.',
 'FUNCTION: Putative metalloproteinase that plays a role in left-right patterning process. {ECO:0000250|UniProtKB:A0A1D5NSK0}.',
 'FUNCTION: Promotes epithelial differentiation by enhancing the sumoylation and activation of CDC42 (PubMed:36369429). Promotes keratinocyte proliferation (PubMed:32012357). This contributes to the maintenance of skin homeostasis by enhancing wound healing after skin injury (By similarity). Acts as a tumor suppressor in epithelial tumors (PubMed:36369429, PubMed:36899004). {ECO:0000250|UniProtKB:A0A1B0GRQ3, ECO:0000269|PubMed:32012357, ECO:0000269|PubMed:36369429, ECO:0000269|PubMed:36899004}.',
 'FUNCTION: Required for the assembly and/or stability of the 40S ribosomal subunit. Required for the processing of the 20S rRNA-precursor to mature 18S rRNA in a late step of the maturation of 40S ribosomal subunits. Also functions as a cell surface receptor for laminin. Plays a role in cell adhesion to the basement membrane and in the consequent activation of signaling transduction pathways. May play a role in cell fate determination and tissue morphogenesis. Also acts as a receptor for several other ligands, including the pathogenic prion protein, viruses, and bacteria. Acts as a PPP1R16B-dependent substrate of PPP1CA. {ECO:0000255|HAMAP-Rule:MF_03016}.',
 'FUNCTION: Cation/chloride cotransporter that may play a role in the control of keratinocyte proliferation. {ECO:0000269|PubMed:11863360}.',
 "FUNCTION: Single-stranded RNA-binding protein that functions in a variety of RNA processes, including alternative splicing, RNA stabilization, and RNA editing (PubMed:24038582, PubMed:24916387, PubMed:27050523, PubMed:30844405, PubMed:31358901, PubMed:34160127). Functions as an enzyme-substrate adapter for the cytidine deaminase APOBEC1. With APOBEC1 forms an mRNA editing complex involved into cytidine to uridine editing of a variety of mRNA molecules (PubMed:24038582, PubMed:24916387, PubMed:30844405). Through the binding of their 3'UTR, also stabilizes a variety of mRNAs and regulates the expression of genes such as the interferon alpha/beta receptor and interleukin-10 (PubMed:34160127). Also involved in the alternative splicing of several genes including TJP1. Binds the pre-mRNA (U)GCAUG consensus sequences in downstream intronic regions of alternative exons, regulating their exclusion and inclusion into mRNAs (PubMed:27050523, PubMed:31358901). Independently of its RNA-binding activity, could negatively regulate MAVS by promoting its lysosomal degradation (By similarity). {ECO:0000250|UniProtKB:A0A8M1NHK4, ECO:0000269|PubMed:24038582, ECO:0000269|PubMed:24916387, ECO:0000269|PubMed:27050523, ECO:0000269|PubMed:30844405, ECO:0000269|PubMed:31358901, ECO:0000269|PubMed:34160127}.",
 'FUNCTION: Component of the intraflagellar transport (IFT) complex B required for transport of proteins in the motile cilium. Required for transport of specific ciliary cargo proteins related to motility, while it is neither required for IFT complex B assembly or motion nor for cilium assembly. Required for efficient coupling between the accumulation of GLI2 and GLI3 at the ciliary tips and their dissociation from the negative regulator SUFU. Plays a key role in maintaining the integrity of the IFT complex B and the proper ciliary localization of the IFT complex B components. Not required for IFT complex A ciliary localization or function. Essential for maintaining proper microtubule organization within the ciliary axoneme. {ECO:0000269|PubMed:31595528}.',
 'FUNCTION: E3 ubiquitin-protein ligase involved in ER-associated protein degradation, preferentially associates with the E2 enzyme UBE2J2. Exploited by viral US11 proteins to mediate HLA class I proteins degradation. {ECO:0000269|PubMed:24807418}.',
 "FUNCTION: Atypical E2F transcription factor that participates in various processes such as angiogenesis and polyploidization of specialized cells. Mainly acts as a transcription repressor that binds DNA independently of DP proteins and specifically recognizes the E2 recognition site 5'-TTTC[CG]CGC-3'. Directly represses transcription of classical E2F transcription factors such as E2F1: component of a feedback loop in S phase by repressing the expression of E2F1, thereby preventing p53/TP53-dependent apoptosis. Plays a key role in polyploidization of cells in placenta and liver by regulating the endocycle, probably by repressing genes promoting cytokinesis and antagonizing action of classical E2F proteins (E2F1, E2F2 and/or E2F3). Required for placental development by promoting polyploidization of trophoblast giant cells. Acts as a promoter of sprouting angiogenesis, possibly by acting as a transcription activator: associates with HIF1A, recognizes and binds the VEGFA promoter, which is different from canonical E2 recognition site, and activates expression of the VEGFA gene. {ECO:0000269|PubMed:15897886, ECO:0000269|PubMed:16179649, ECO:0000269|PubMed:18202719, ECO:0000269|PubMed:22903062}.",
 'FUNCTION: Activates ubiquitin by first adenylating its C-terminal glycine residue with ATP, and thereafter linking this residue to the side chain of a cysteine residue in E1, yielding a ubiquitin-E1 thioester and free AMP (PubMed:35970836, PubMed:35986001). Specific for ubiquitin, does not activate ubiquitin-like peptides. Also activates UBD/FAT10 conjugation via adenylation of its C-terminal glycine (PubMed:17889673, PubMed:35970836, PubMed:35986001). Differs from UBE1 in its specificity for substrate E2 charging. Does not charge cell cycle E2s, such as CDC34. Essential for embryonic development. Isoform 2 may play a key role in ubiquitin system and may influence spermatogenesis and male fertility. {ECO:0000269|PubMed:15202508, ECO:0000269|PubMed:17597759, ECO:0000269|PubMed:17889673, ECO:0000269|PubMed:35970836, ECO:0000269|PubMed:35986001}.',
 'FUNCTION: Tethers the endoplasmic reticulum to the cell membrane and promotes the formation of appositions between the endoplasmic reticulum and the cell membrane. Binds glycerophospholipids in a barrel-like domain and may play a role in cellular lipid transport. Plays a role in FGF signaling via its role in the rapid internalization of FGFR1 that has been activated by FGF1 binding; this occurs most likely via the AP-2 complex. Promotes the localization of SACM1L at endoplasmic reticulum-plasma membrane contact sites (EPCS) (PubMed:27044890). {ECO:0000269|PubMed:17360437, ECO:0000269|PubMed:20833364, ECO:0000269|PubMed:23791178, ECO:0000269|PubMed:24847877, ECO:0000269|PubMed:27044890}.',
 'FUNCTION: Binds glycerophospholipids in a barrel-like domain and may play a role in cellular lipid transport (By similarity). Tethers the endoplasmic reticulum to the cell membrane and promotes the formation of appositions between the endoplasmic reticulum and the cell membrane. {ECO:0000250, ECO:0000269|PubMed:23791178}.',
 'FUNCTION: Component of the Mediator complex, a coactivator involved in the regulated transcription of nearly all RNA polymerase II-dependent genes. Mediator functions as a bridge to convey information from gene-specific regulatory proteins to the basal RNA polymerase II transcription machinery. Mediator is recruited to promoters by direct interactions with regulatory proteins and serves as a scaffold for the assembly of a functional preinitiation complex with RNA polymerase II and the general transcription factors.',
 'FUNCTION: Tube-forming lipid transport protein which mediates the transfer of lipids between membranes at organelle contact sites (PubMed:35499567). Required for retrograde traffic of vesicle clusters in the early endocytic pathway to the Golgi complex (PubMed:20163565, PubMed:35499567). {ECO:0000269|PubMed:20163565, ECO:0000269|PubMed:35499567}.',
 None]